package com.betarealms.hammerswelldone.events;

import com.betarealms.hammerswelldone.types.Type;
import com.betarealms.hammerswelldone.utils.ToolManager;
import java.util.Objects;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.PrepareSmithingEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

/**
 * This runs when a player inputs a smithing recipe.
 */
public class OnPrepareSmithing implements Listener {

  /**
   * This is used to block upgrading SUPER tools to netherite and to handle
   * item renaming when upgrading other tools to netherite.
   *
   * @param event PrepareItemCraftEvent
   */
  @EventHandler
  public void onPrepareSmithing(PrepareSmithingEvent event) {
    // Get the items in the input slots
    ItemStack[] inputs = event.getInventory().getContents();

    // Check if item in slot 1 is a custom tool
    if (inputs[1] != null
        && ToolManager.isCustomTool(Objects.requireNonNull(inputs[1].getItemMeta()))) {
      // Is this a SUPER?
      if (ToolManager.decodeType(inputs[1].getItemMeta().getCustomModelData()) == Type.SUPER) {
        event.setResult(null);
        return;
      }

      // Get result item as generated by smithing table
      ItemStack resultItem = event.getResult();

      // Get result meta
      assert resultItem != null;
      ItemMeta resultMeta = resultItem.getItemMeta();

      // Get result custom model data
      assert resultMeta != null;
      int resultCustomModelData = resultMeta.getCustomModelData();

      // Get desired item
      ItemStack newItem = ToolManager.getItemStack(
          resultItem.getType(),
          ToolManager.decodeType(resultCustomModelData),
          ToolManager.decodeTier(resultCustomModelData));

      // Get and set the display name
      resultMeta.setDisplayName(Objects.requireNonNull(newItem.getItemMeta()).getDisplayName());
      resultItem.setItemMeta(resultMeta);

      // Set the result
      event.setResult(newItem);
    }
  }
}
